[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.5"
chrono = { version = "0.4.28", default-features = false }
ic-cdk = "0.10.0"
serde = "1.0.188"
