[package]
name = "publisher"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.2"
ic-cdk = "0.10.0"
ic-cdk-macros = "0.7.0"
serde = "1.0.176"
serde_derive = "1.0.176"
